/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#define SIZE_TASK_STACK				1024U
#define SIZE_SCHED_STACK			1024U

#define SRAM_START 					0x20000000U
#define SIZE_SRAM 					( (128) * (1024) )
#define SRAM_END 					( (SRAM_START) + (SIZE_SRAM) )

#define T1_STACK_START 				SRAM_END
#define T2_STACK_START 				( (SRAM_END) - (1 * SIZE_TASK_STACK) )
#define T3_STACK_START 				( (SRAM_END) - (2 * SIZE_TASK_STACK) )
#define T4_STACK_START 				( (SRAM_END) - (3 * SIZE_TASK_STACK) )
#define SCHED_STACK_START 			( (SRAM_END) - (4 * SIZE_TASK_STACK) )

#define TICK_HZ						1000U
#define SYSTICK_TIM_CLK				HSI_CLOCK
#define HSI_CLOCK 					16000000U

void init_systick_timer (uint32_t tick_hz);

void Task1_Handler(void){
	while(1){

	}
}
void Task2_Handler(void){
	while(1){

	}
}
void Task3_Handler(void){
	while(1){

	}
}
void Task4_Handler(void){
	while(1){

	}
}

void init_systick_timer (uint32_t tick_hz){

	uint32_t *pSRVR = (uint32_t *)0xE000E014;
	uint32_t *pSCR =  (uint32_t *)0xE000E010;

	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

	//Clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//Load the value into SVR
	*pSRVR |= count_value;

	//Enable SysTick exception request,Clock source - Processor, Enable the counter
	*pSCR |= ( 1 << 1) | ( 1 << 2) | (1 << 0);

}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	//__asm volatile("MSR MSP, R0");
	__asm volatile("MSR MSP,%0": : "r" (sched_top_of_stack) : );
	__asm volatile("BX LR");
}
int main(void)
{
	init_scheduler_stack(SCHED_STACK_START);

	init_systick_timer(TICK_HZ);

	while(1){

	}
}
